# Generated by Django 4.2.16 on 2024-11-20 07:36

from django.db import migrations, models
import django.db.models.deletion


def split_datetime(apps, schema_editor):
    Reserva = apps.get_model('restaurante', 'Reserva')
    for reserva in Reserva.objects.all():
        reserva.fecha = reserva.fecha_hora.date()
        reserva.hora = reserva.fecha_hora.time()
        reserva.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(max_length=15)),
                ('fecha_hora', models.DateTimeField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.mesa')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
