# Generated by Django 4.2.16 on 2024-11-20 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mesa_reserva_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
