# Generated by Django 4.2.16 on 2024-11-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_reserva_fecha_hora_reserva_fecha_reserva_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
