# Generated by Django 4.2.16 on 2024-11-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_imagencarrusel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.CharField(choices=[('Entrantes', 'Entrantes'), ('Plato Principal', 'Plato Principal'), ('Postres', 'Postres'), ('Bebidas', 'Bebidas')], max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
