# Generated by Django 4.2.16 on 2024-11-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='num_personas',
            field=models.IntegerField(default=1),
        ),
    ]
