# Generated by Django 4.2.16 on 2024-11-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_mesa_disponible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GaleriaFoto',
        ),
    ]
