# Generated by Django 4.2.16 on 2024-11-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_delete_galeriafoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(default=True),
        ),
    ]
