# Generated by Django 4.2.16 on 2024-12-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_imagengaleria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagengaleria',
            name='fecha_subida',
        ),
    ]
