# Generated by Django 4.2.16 on 2024-12-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_imagengaleria_fecha_subida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagengaleria',
            name='imagen',
            field=models.ImageField(upload_to='historia/'),
        ),
    ]
