# Generated by Django 4.2.16 on 2024-12-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_imagengaleria_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenGaleria',
        ),
    ]
